- name: Setup firewall rule for ingress RKE access (External)
  ufw:
    rule: allow
    port: '6443'
    proto: 'tcp'
    src: '{{ rke_controller_ip }}'

- name: Setup firewall rule for ingress RKE access (Static)
  ufw:
    rule: allow
    port: '6443'
    proto: 'tcp'
    src: '{{ rke_allowed_static }}'

# - name: Setup firewall rules for ingress from loadbalancers
#   include_tasks: firewall_nodes.yml
#   loop: "{{ groups.lb | map('extract', hostvars, ['ansible_facts', 'eth0', 'ipv4', 'address']) | list }}"
#   loop_control:
#     loop_var: host_ip
#   vars:
#     rules:
#       - { proto: 'tcp', port: 80 }
#       - { proto: 'tcp', port: 443 }
#   when: "'nodes' in group_names"

- name: Setup firewall rule for public ingress
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: 'tcp'
  loop:
    - '80'
    - '443'

- name: Setup firewall rules for master-master communication
  include_tasks: firewall_nodes.yml
  loop: "{{ groups.master_nodes | map('extract', hostvars, ['ansible_facts', 'eth0', 'ipv4', 'address'])| select('defined') | list  }}"
  loop_control:
    loop_var: host_ip
  vars:
    rules:
      - { proto: 'tcp', port: 2376 }
      - { proto: 'tcp', port: 2379 }
      - { proto: 'tcp', port: 2380 }
      - { proto: 'tcp', port: 6443 }
      - { proto: 'udp', port: 8472 }
      - { proto: 'tcp', port: 10250 }
      - { proto: 'tcp', port: '30000:32767' }
      - { proto: 'udp', port: '30000:32767' }
  when: "'master_nodes' in group_names"

- name: Setup firewall rules for master-worker communication
  include_tasks: firewall_nodes.yml
  loop: "{{ groups.worker_nodes | map('extract', hostvars, ['ansible_facts', 'eth0', 'ipv4', 'address'])| select('defined') | list  }}"
  loop_control:
    loop_var: host_ip
  vars:
    rules:
      - { proto: 'tcp', port: 2376 }
      - { proto: 'tcp', port: 6443 }
      - { proto: 'udp', port: 8472 }
      - { proto: 'tcp', port: '30000:32767' }
      - { proto: 'udp', port: '30000:32767' }
  when: "'master_nodes' in group_names"

- name: Setup firewall rules for worker-master communication
  include_tasks: firewall_nodes.yml
  loop: "{{ groups.master_nodes | map('extract', hostvars, ['ansible_facts', 'eth0', 'ipv4', 'address']) | select('defined') | list }}"
  loop_control:
    loop_var: host_ip
  vars:
    rules:
      - { proto: 'tcp', port: 2376 }
      - { proto: 'udp', port: 8472 }
      - { proto: 'tcp', port: 10250 }
      - { proto: 'tcp', port: '30000:32767' }
      - { proto: 'udp', port: '30000:32767' }
  when: "'worker_nodes' in group_names"

- name: Setup firewall rules for worker-worker communication
  include_tasks: firewall_nodes.yml
  loop: "{{ groups.worker_nodes | map('extract', hostvars, ['ansible_facts', 'eth0', 'ipv4', 'address']) | select('defined') | list }}"
  loop_control:
    loop_var: host_ip
  vars:
    rules:
      - { proto: 'tcp', port: 2376 }
      - { proto: 'udp', port: 8472 }
      - { proto: 'tcp', port: '30000:32767' }
      - { proto: 'udp', port: '30000:32767' }
  when: "'worker_nodes' in group_names"
